version: '3.1'

services:

    # Web Server Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - '8080:80'
        volumes:
            - .:/var/www/html
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/logs:/var/log/nginx
        depends_on:
            - app
            - db

    #Database Service
    db:
        image: mysql:8.0.29-oracle
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        ports:
            - "3366:3306"
        environment:
            MYSQL_DATABASE: phonestore
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_USER: root
#    db:
#        image: postgres
#        container_name: postgres
#        volumes:
#            - ./postgresql/data:/var/lib/postgresql/data
#        ports:
#            - "5432:5432"
#        environment:
#            POSTGRES_DB: sell_phone
#            POSTGRES_USER: root
#            POSTGRES_PASSWORD: password

    # Application Service
    app:
        container_name: phonestore
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        working_dir: /var/www/html

    #phpMyAdmin Service
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: phpmyadmin
#        ports:
#            - "3400:80"
#        depends_on:
#            - db
#    pgadmin:
#        image: dpage/pgadmin4
#        container_name: pgAdmin
#        ports:
#            - "5050:80"
#        depends_on:
#            - db
#        environment:
#            PGADMIN_DEFAULT_EMAIL: hanieasemi76@gmail.com
#            PGADMIN_DEFAULT_PASSWORD: password
